---
author:
  name: Мартынов Николай Алексеевич
title: "Лабораторная работа №1"
subtitle: "Подготовка рабочего пространства"
---

# Цель

## Цель работы

Подготовить рабочее пространство для выполнения лабораторных работ по дисциплине «Computer Skills for Scientific Writing».

# Выполнение работы

## Структура курса

- `COURSE = practical-scientific-writing`
- каталоги `lab01`–`lab08`
- отдельные каталоги `report` и `presentation` для лабораторной работы №1

## Git и Git Flow

- `master` — стабильная ветка
- `develop` — ветка разработки
- `release/*` — подготовка релизов
- теги версий имеют префикс `v`

## Conventional Commits

Основные сообщения коммитов:

```text
feat(main): make course structure
feat(lab01): add laboratory report
feat(lab01): add laboratory presentation
chore(release): release 1.1.0
```

## Версионирование

- `v1.0.0` — базовая структура курса
- `v1.1.0` — лабораторная работа №1

# Результаты

## Результат

Подготовлены:

- структура курса;
- отчёт лабораторной работы №1;
- презентация лабораторной работы №1;
- ветки `master` и `develop`;
- Conventional Commits;
- релиз `v1.1.0`.

# Заключение

## Вывод

Репозиторий подготовлен для дальнейшего выполнения лабораторных работ и ведения проекта с использованием Git Flow и семантического версионирования.
