project:
  title: "presentation"
  output-dir: "_output"

lang: ru-RU
slide-level: 2
embed-resources: true

format:
  revealjs:
    transition: slide
    slide-number: true
    theme: beige
  beamer:
    pdf-engine: xelatex
    aspectratio: 169
    toc: true
    mainfont: "DejaVu Serif"
    sansfont: "DejaVu Sans"
    monofont: "DejaVu Sans Mono"
